import type { NextPage } from "next";
import Head from "next/head";
import { HomePage, AboutPage } from "../components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Thinesh Rasla | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </div>
  );
};

export default Home;
