import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Container } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Thinesh Rasla | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        as={"main"}
        bg={"brand.dark-navy"}
        maxW={"screen"}
        height={"100vh"}
      >
        Hello Rasla
      </Container>
    </div>
  );
};

export default Home;
